
import { Geist, Geist_Mono, Lexend } from "next/font/google";

import "./globals.css";
import { TabProvider } from "./TabContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
  weight: ["400","500","600","700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lexend.variable} antialiased font-sans`}
      >
        <TabProvider>
          {children}
        </TabProvider>
      </body>
    </html>
  );
}
